name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the CALC Docker image
      run: docker build -t calc-image-lab07-testing -f ./src/calc/Dockerfile_test ./src/calc
