name: INTEGRATION AND UNIT TESTS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-test-calc-image:
    name: Build and Test CALC Image (UNIT TEST)
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build and run the CALC Docker image
      run: |
          docker build -t calc-image-lab07-testing -f ./src/calc/Dockerfile_test ./src/calc
          docker run -d -p 5000:5000 --name calc-container-lab07-test calc-image-lab07-testing

    - name: Install Node.js
      uses: actions/setup-node@v4

    - name: Install Newman
      run: npm install -g newman
    
    - name: Run the CALC tests
      run: newman run ./tests/calc_ut.postman_collection.json

  build-and-test-string-image:
    name: Build and Test STRING Image (UNIT TEST)
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build and run the STRING Docker image
      run: |
          docker build -t string-image-lab07-testing -f ./src/string/Dockerfile_test ./src/string
          docker run -d -p 5000:5000 --name string-container-lab07-test string-image-lab07-testing

    - name: Install Node.js
      uses: actions/setup-node@v4

    - name: Install Newman
      run: npm install -g newman
    
    - name: Run the STRING tests
      run: newman run ./tests/string_ut.postman_collection.json

  build-and-test-everything:
    name: Build and Test Everything (INTEGRATION TEST)
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build and run the whole system using Docker Compose
      run: docker compose -f src/docker-compose.yml up -d

    - name: Install Node.js
      uses: actions/setup-node@v4

    - name: Install Newman
      run: npm install -g newman
    
    - name: Run the STRING tests
      run: newman run ./tests/integration.postman_collection.json